package com.kuaixiu.card.entity;

import com.common.base.entity.BaseEntity;

import java.util.Date;

public class SuperToChannel extends BaseEntity{

    private static final long serialVersionUID = 2350425408086577504L;
    /** 号卡iccid*/
    private String iccid;

    /** 号卡推送订单号(转转生成)*/
    private String orderNo;

    /** (站点-用户)物流公司*/
    private String expressName;

    /** (站点-用户)物流单号*/
    private String expressNumber;

    /** (站点-用户)发货站点id*/
    private String sendStationId;

    /** (站点-用户)发货时间*/
    private String operateTime;

    /** (站点-用户)发货城市*/
    private String sendCity;

    /** 超人-电渠 推送状态 0成功  1失败*/
    private Integer status;

    /** 推送错误返回信息*/
    private String returnCode;

    /** 推送总次数*/
    private Integer sendSum;

    /** 最近一次推送时间*/
    private Date sendTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_super_to_channel.iccid
     *
     * @return the value of hk_super_to_channel.iccid
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public String getIccid() {
        return iccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_super_to_channel.iccid
     *
     * @param iccid the value for hk_super_to_channel.iccid
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public void setIccid(String iccid) {
        this.iccid = iccid == null ? null : iccid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_super_to_channel.order_no
     *
     * @return the value of hk_super_to_channel.order_no
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_super_to_channel.order_no
     *
     * @param orderNo the value for hk_super_to_channel.order_no
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_super_to_channel.express_name
     *
     * @return the value of hk_super_to_channel.express_name
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public String getExpressName() {
        return expressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_super_to_channel.express_name
     *
     * @param expressName the value for hk_super_to_channel.express_name
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public void setExpressName(String expressName) {
        this.expressName = expressName == null ? null : expressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_super_to_channel.express_number
     *
     * @return the value of hk_super_to_channel.express_number
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public String getExpressNumber() {
        return expressNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_super_to_channel.express_number
     *
     * @param expressNumber the value for hk_super_to_channel.express_number
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public void setExpressNumber(String expressNumber) {
        this.expressNumber = expressNumber == null ? null : expressNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_super_to_channel.send_station_id
     *
     * @return the value of hk_super_to_channel.send_station_id
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public String getSendStationId() {
        return sendStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_super_to_channel.send_station_id
     *
     * @param sendStationId the value for hk_super_to_channel.send_station_id
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public void setSendStationId(String sendStationId) {
        this.sendStationId = sendStationId == null ? null : sendStationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_super_to_channel.send_timestamp
     *
     * @return the value of hk_super_to_channel.send_timestamp
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public String getOperateTime() {
        return operateTime;
    }

    public void setOperateTime(String operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_super_to_channel.send_city
     *
     * @return the value of hk_super_to_channel.send_city
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public String getSendCity() {
        return sendCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_super_to_channel.send_city
     *
     * @param sendCity the value for hk_super_to_channel.send_city
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public void setSendCity(String sendCity) {
        this.sendCity = sendCity == null ? null : sendCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_super_to_channel.status
     *
     * @return the value of hk_super_to_channel.status
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_super_to_channel.status
     *
     * @param status the value for hk_super_to_channel.status
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_super_to_channel.return_code
     *
     * @return the value of hk_super_to_channel.return_code
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_super_to_channel.return_code
     *
     * @param returnCode the value for hk_super_to_channel.return_code
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_super_to_channel.send_sum
     *
     * @return the value of hk_super_to_channel.send_sum
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public Integer getSendSum() {
        return sendSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_super_to_channel.send_sum
     *
     * @param sendSum the value for hk_super_to_channel.send_sum
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public void setSendSum(Integer sendSum) {
        this.sendSum = sendSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_super_to_channel.send_time
     *
     * @return the value of hk_super_to_channel.send_time
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_super_to_channel.send_time
     *
     * @param sendTime the value for hk_super_to_channel.send_time
     *
     * @mbg.generated Fri Jul 27 15:41:52 CST 2018
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }
}